

$(document).ready(function(){
    $("#a").click(function(){
        $("#a1").modal();
    });
});

$(document).ready(function(){
    $("#b").click(function(){
        $("#b1").modal();
    });
});
$(document).ready(function(){
    $("#c").click(function(){
        $("#c1").modal();
    });
});

$(document).ready(function(){
    $("#d").click(function(){
        $("#d1").modal();
    });
});
$(document).ready(function(){
    $("#e").click(function(){
        $("#e1").modal();
    });
});
$(document).ready(function(){
    $("#f").click(function(){
        $("#f1").modal();
    });
});
$(document).ready(function(){
    $("#g").click(function(){
        $("#g1").modal();
    });
});
$(document).ready(function(){
    $("#h").click(function(){
        $("#h1").modal();
    });
});
$(document).ready(function(){
    $("#i").click(function(){
        $("#i1").modal();
    });
});